In [7]:
import pandas as pd

In [8]:
df=pd.read_csv('RME_Material_Movement_with_cos_090623.csv',encoding='utf-8-sig')
df

,Item Code,Item Desc,Uom,From,To,Project,Project Num,Trx Id,Exp id,Task Num,...,Trx Type,Move Order Num,Date,Unit Cost,Quantities,Po Num,Total Amount,Project Area,Issued Type,Comment
0,ZC03001372,بريزة خارج الحائط,ECH,El Khatatba Bridge-0143,NaN,El Khatatba Bridge,143.0,47336739.0,NaN,SE-19,...,Move Order Issue on Project,RE3-23,28-Dec-21,0,-3.0,NaN,0,NaN,supplier,NaN
1,ZC03001366,لاكور ماسورة 1 بوصة EMT,ECH,El Khatatba Bridge-0143,NaN,El Khatatba Bridge,143.0,50612566.0,NaN,SE-19,...,Move Order Issue on Project,RE3-33,28-Feb-22,0,-5.0,NaN,0,NaN,supplier,NaN
2,ZC01003004,كارت فحص دورى لطفايات الحريق,ECH,El Khatatba Bridge-0143,NaN,El Khatatba Bridge,143.0,58920590.0,NaN,SE-19,...,Move Order Issue on Project,RE3-81,25-Dec-22,0,-5.0,NaN,0,NaN,NaN,NaN
3,ZC03001365,لاكور ماسورة على فلكسبيل 1 بوصة EMT,ECH,El Khatatba Bridge-0143,NaN,El Khatatba Bridge,143.0,50612565.0,NaN,SE-19,...,Move Order Issue on Project,RE3-33,28-Feb-22,0,-10.0,NaN,0,NaN,supplier,NaN
4,ZC01003003,مثلث عاكس,ECH,El Khatatba Bridge-0143,NaN,El Khatatba Bridge,143.0,61735684.0,NaN,SE-19,...,Move Order Issue on Project,RE3-100,08-May-23,0,-1.0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5083,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5085,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5086,Page 1 of 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df[df['Item Desc'].str.contains('حديد تسليح')==True]
df

,Item Code,Item Desc,Uom,From,To,Project,Project Num,Trx Id,Exp id,Task Num,...,Trx Type,Move Order Num,Date,Unit Cost,Quantities,Po Num,Total Amount,Project Area,Issued Type,Comment
56,150010000008,حديد تسليح قطر 25 مم,TON,El Khatatba Bridge-0143,NaN,El Khatatba Bridge,143.0,41117286.0,NaN,302,...,PO Receipt,,29-Jun-21,"14,500.00",67.360,51791.0,"976,720",NaN,NaN,NaN
57,150010000007,حديد تسليح قطر 22 مم,TON,El Khatatba Bridge-0143,NaN,El Khatatba Bridge,143.0,41117290.0,NaN,302,...,PO Receipt,,29-Jun-21,"14,500.00",50.640,51791.0,"734,280",NaN,NaN,NaN
58,150010000004,حديد تسليح قطر 16 مم,TON,El Khatatba Bridge-0143,NaN,El Khatatba Bridge,143.0,41117294.0,NaN,302,...,PO Receipt,,29-Jun-21,"14,500.00",5.860,51791.0,"84,970",NaN,NaN,NaN
59,150010000001,حديد تسليح قطر 10مم,TON,El Khatatba Bridge-0143,NaN,El Khatatba Bridge,143.0,41117298.0,NaN,302,...,PO Receipt,,29-Jun-21,"14,500.00",15.460,51791.0,"224,170",NaN,NaN,NaN
83,150010000001,حديد تسليح قطر 10مم,TON,El Khatatba Bridge-0143,NaN,El Khatatba Bridge,143.0,42729027.0,NaN,302,...,PO Receipt,,21-Aug-21,"14,500.00",10.660,51791.0,"154,570",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,150010000002,حديد تسليح قطر 12 مم,TON,El Khatatba Bridge-0143,RING ROAD BRIDGE-0122,El Khatatba Bridge,143.0,45409900.0,NaN,NaN,...,Intransit Shipment,,17-Nov-21,"14,698.76",-20.000,NaN,"-293,975",NaN,NaN,NaN
5006,150010000004,حديد تسليح قطر 16 مم,TON,El Khatatba Bridge-0143,Abou Ghaleb Bridge-0157,El Khatatba Bridge,143.0,51816334.0,NaN,NaN,...,Intransit Shipment,,20-Apr-22,"19,630.17",-8.000,NaN,"-157,041",NaN,NaN,NaN
5007,150010000002,حديد تسليح قطر 12 مم,TON,El Khatatba Bridge-0143,Abou Ghaleb Bridge-0157,El Khatatba Bridge,143.0,51913690.0,NaN,NaN,...,Intransit Shipment,,24-Apr-22,"17,973.58",-12.000,NaN,"-215,683",NaN,NaN,NaN
5036,150080000071,حديد تسليح قطر 22 مم طول 1.5 متر Cut Off,TON,El Khatatba Bridge-0143,The Open Channel-0160,El Khatatba Bridge,143.0,57616201.0,NaN,NaN,...,Intransit Shipment,,15-Nov-22,"18,070.00",-0.737,NaN,"-13,318",NaN,NaN,NaN
5067,150010000001,حديد تسليح قطر 10مم,TON,NaN,NaN,NaN,NaN,46180017.0,2112866,NaN,...,RME Site Return,,09-Dec-21,"14,500.00",2.500,NaN,"36,250",NaN,NaN,NaN